site_name: Personal Movie Recommender
site_description: A smart hybrid movie recommendation system built with Python & Gradio
site_author: Gurami Esartia
repo_url: https://github.com/Gurjaka/Personal-movie-recommendation-model

theme:
  name: material
  palette:
    - scheme: slate
      primary: blue grey
      accent: cyan
  font:
    text: Roboto
    code: Fira Code
  logo: assets/tbc-logo.png
  favicon: assets/tbc-logo.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - navigation.sections
    - navigation.expand
    - navigation.footer

extra:
  generator: false

extra_css:
  - stylesheets/nord.css

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options.extra:
            paths:
              - src
            show_source: true
            docstring_style: google

nav:
  - Home: index.md
  - About: about.md
  - Report: report.md
  - Usage: usage.md
  - API Reference:
      - Main: reference/main.md
      - Train: reference/train.md
      - Utils: reference/utils.md
      - Visualize: reference/visualize.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
